#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# couple-chat Off-Box Backup Sync Script
# 
# Syncs PocketBase snapshot archives generated by PocketBase's internal backup
# schedule (/opt/couple-chat/pb_data/backups/*.zip) to an off-box remote target
# via rsync or scp. No superuser or API credentials required.
# ==============================================================================

BACKUP_DIR="${BACKUP_DIR:-/opt/couple-chat/pb_data/backups}"
REMOTE_TARGET="${1:-${REMOTE_TARGET:-}}"
SYNC_TOOL="${SYNC_TOOL:-rsync}"
SSH_KEY="${SSH_KEY:-}"
SSH_PORT="${SSH_PORT:-22}"
DRY_RUN="${DRY_RUN:-0}"

log() {
    echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $*"
}

if [[ -z "${REMOTE_TARGET}" ]]; then
    echo "Error: Remote target destination not specified." >&2
    echo "Usage: $0 <user@remote-host:/path/to/backups>" >&2
    echo "       or set REMOTE_TARGET environment variable." >&2
    exit 1
fi

if [[ ! -d "${BACKUP_DIR}" ]]; then
    echo "Error: Backup directory '${BACKUP_DIR}' does not exist." >&2
    exit 1
fi

# Locate the newest .zip backup archive
LATEST_BACKUP=""
shopt -s nullglob
backup_files=("${BACKUP_DIR}"/*.zip)
shopt -u nullglob

if [[ ${#backup_files[@]} -eq 0 ]]; then
    echo "Error: No backup archives (*.zip) found in ${BACKUP_DIR}." >&2
    exit 1
fi

for f in "${backup_files[@]}"; do
    if [[ -z "${LATEST_BACKUP}" || "${f}" -nt "${LATEST_BACKUP}" ]]; then
        LATEST_BACKUP="${f}"
    fi
done

log "Found latest backup archive: ${LATEST_BACKUP} ($(du -h "${LATEST_BACKUP}" | cut -f1))"
log "Syncing to off-box target: ${REMOTE_TARGET} using ${SYNC_TOOL}..."

if [[ "${DRY_RUN}" == "1" || "${DRY_RUN}" == "true" ]]; then
    log "[DRY-RUN] Would sync ${LATEST_BACKUP} to ${REMOTE_TARGET} using ${SYNC_TOOL}."
    log "Off-box backup sync completed successfully."
    exit 0
fi

case "${SYNC_TOOL}" in
    rsync)
        RSYNC_SSH_OPTS="ssh -p ${SSH_PORT}"
        if [[ -n "${SSH_KEY}" ]]; then
            RSYNC_SSH_OPTS="ssh -i ${SSH_KEY} -p ${SSH_PORT}"
        fi

        rsync -avz --partial -e "${RSYNC_SSH_OPTS}" "${LATEST_BACKUP}" "${REMOTE_TARGET}"
        ;;
    scp)
        SCP_OPTS=(-P "${SSH_PORT}" -p)
        if [[ -n "${SSH_KEY}" ]]; then
            SCP_OPTS+=(-i "${SSH_KEY}")
        fi

        scp "${SCP_OPTS[@]}" "${LATEST_BACKUP}" "${REMOTE_TARGET}"
        ;;
    *)
        echo "Error: Unsupported SYNC_TOOL '${SYNC_TOOL}'. Must be 'rsync' or 'scp'." >&2
        exit 1
        ;;
esac

log "Off-box backup sync completed successfully."
